# Generated by Django 5.2.6 on 2025-09-19 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('hi', 'Hindi'), ('en', 'English'), ('mr', 'Marathi'), ('od', 'Odiya')], default='en', max_length=10)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=10)),
                ('student_class', models.CharField(choices=[('6', '6th'), ('7', '7th'), ('8', '8th'), ('9', '9th'), ('10', '10th'), ('11', '11th'), ('12', '12th')], max_length=5)),
                ('board', models.CharField(choices=[('up', 'UP Board'), ('cbse', 'CBSE'), ('icse', 'ICSE')], max_length=20)),
                ('subjects', models.TextField(help_text='Comma separated subject names')),
                ('school_name', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
