# Generated by Django 5.2.6 on 2025-09-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('board', models.CharField(choices=[('up', 'UP Board'), ('cbse', 'CBSE'), ('icse', 'ICSE')], max_length=20)),
                ('student_class', models.CharField(choices=[('6', '6th'), ('7', '7th'), ('8', '8th'), ('9', '9th'), ('10', '10th'), ('11', '11th'), ('12', '12th')], max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='accounts.subject'),
        ),
    ]
